<?xml version="1.0" encoding="utf-8"?><Database Name="UserDb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.5;Initial Catalog=UserDb;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="UserDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student_new" Member="Student_news">
    <Type Name="Student_new">
      <Column Name="Rollno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Class" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Marks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>